# Generated by Django 4.2.6 on 2023-11-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('otc', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=3, null=True)),
                ('summer', models.CharField(blank=True, max_length=3, null=True)),
                ('autumn', models.CharField(blank=True, max_length=3, null=True)),
                ('spring', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NE', 'new'), ('PE', 'pending'), ('AC', 'accepted'), ('RE', 'rejected')], default='NE', max_length=30)),
                ('beauty_title', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('other_titles', models.CharField(max_length=30)),
                ('connect', models.CharField(max_length=30)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='beauty.coords')),
                ('images', models.ManyToManyField(to='beauty.images')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='beauty.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beauty.customuser')),
            ],
        ),
    ]
