# Generated by Django 4.2.6 on 2023-11-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_customuser_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mail',
            new_name='email',
        ),
    ]
